# Generated by Django 2.2.9 on 2020-01-11 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='Your_Appreciation_or_Critics_about_this_movie',
            field=models.TextField(max_length=200000, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='journal',
            name='Your_Post_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
