# Generated by Django 2.2.9 on 2020-01-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200109_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(max_length=5789, primary_key=True, serialize=False),
        ),
    ]
